### ISSUE TITLE
create EHR on server when a patient is created

### ISSUE THREAD

**Issue by ppazos** [ppazos/notes#37]
* save the ehr uid in the patient domain
* update the commit to use the patient's EHR uid

**Comment by ppazos** [comment]
To update the commit we need a class that models the commit and links the committer, the patient and the note. Also that can be used to maintain the commit status (pending, completed) instead of relying on the filesystem folders.

**Comment by ppazos** [comment]
Getting an error when processing the response for createEHR from server

org.quartz.JobExecutionException: java.lang.NoClassDefFoundError: org/cyberneko/html/parsers/SAXParser
        at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:111)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

Try adding the jar

**Comment by ppazos** [comment]
this is working
